name: Copy Blips to centralized Tech Radar
description: "copy and push files from current repository to a centralized tech radar repository"

inputs:
  tech-radar-repo:
    description: "The repository to copy the blips to"
    required: true
    default: "tech-radar"
  source-path:
    description: "The path to the blips in the current repository"
    required: true
    default: "data/radar"
  commit-message:
    description: "The commit message to use when pushing the blips"
    required: true
    default: "doc: Add blips from repository"
  commit-email:
    description: "The email to use when pushing the blips"
    required: true

# run this workflow to submit you tech radar blips to the centralized tech radar
runs:
  using: "composite"
  steps:
    # Checout local repository
    - name: Checkout local repository
      run: echo "git clone ${{ inputs.source-path }}"
      shell: bash
    # Checkout tech radar repository
    - name: Checkout tech radar repository
      run: echo "git clone ${{ inputs.tech-radar-repo }}/data/radar"
      shell: bash
    - name: checkout branch
      run: echo "checkout brach"
      shell: bash
#      - name: Copy blips to tech radar
#        run: |
#          cp -r ${{ inputs.source-path }}/* $HOME/${{ inputs.tech-radar }}/data/radar
#      # Push blips to tech radar
#      - name: Push blips to tech radar
#        run: |
#          git config --global user.email "${{ inputs.commit-email }}"
#          git config --global user.name "GitHub Actions"
#          cd $HOME/tech-radar
#          git add .
#          git commit -m "${{ inputs.commit-message }}"
#          git push

