name: Copy Blips to centralized Tech Radar
description: "copy and push files from current repository to a centralized tech radar repository"

inputs:
  tech-radar-repo:
    description: "The repository to copy the blips to"
    required: true
    default: "Showoffninja/tech_radar_test.git"
  source-repo:
    description: "The path to the blips in the current repository"
    required: true
    default: "data/radar"
  commit-message:
    description: "The commit message to use when pushing the blips"
    required: true
    default: "doc: Add blips from repository"
  commit-email:
    description: "The email to use when pushing the blips"
    required: true

# run this workflow to submit you tech radar blips to the centralized tech radar
runs:
  using: "composite"
  steps:
    # Checout local repository
    - name: Checkout local repository
      run: echo "git clone https://github.com/${{ inputs.source-path }}.git"
      shell: bash
    # Checkout tech radar repository
    - name: Checkout tech radar repository
      run: echo "git clone --single-branch upload https://github.com/${{ inputs.tech-radar-repo }}.git"
      shell: bash
    # Copy blips
    - name: Copy blips to tech radar
      run: |
        destination_repo_name="${{ inputs.tech-radar-repo }}"
        destination_repo_name="${destination_repo_name##*/}"
        source_repo_name="${{ inputs.source-repo }}"
        source_repo_name="${source_repo_name##*/}"
        shopt -s nullglob
        cp -r ${source_repo_name}/data/radar/*.md ${destination_repo_name}/data/radar/
      shell: bash
    # Push blips to tech radar
    - name: Push blips to tech radar
      run: |
        echo "cd $HOME/tech-radar"
        echo "git config --global user.email ${{ inputs.commit-email }}"
        echo "git config --global user.name GitHub Actions"
        echo "git add ."
        echo "git commit -m ${{ inputs.commit-message }}"
        echo "git push"
      shell: bash
